// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/msg_manage_mayaname.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	common "gitlab.com/mayachain/mayanode/common"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgManageMAYAName struct {
	Name              string                                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Chain             gitlab_com_mayachain_mayanode_common.Chain    `protobuf:"bytes,2,opt,name=chain,proto3,casttype=gitlab.com/mayachain/mayanode/common.Chain" json:"chain,omitempty"`
	Address           gitlab_com_mayachain_mayanode_common.Address  `protobuf:"bytes,3,opt,name=address,proto3,casttype=gitlab.com/mayachain/mayanode/common.Address" json:"address,omitempty"`
	Coin              common.Coin                                   `protobuf:"bytes,4,opt,name=coin,proto3" json:"coin"`
	ExpireBlockHeight int64                                         `protobuf:"varint,5,opt,name=expire_block_height,json=expireBlockHeight,proto3" json:"expire_block_height,omitempty"`
	PreferredAsset    common.Asset                                  `protobuf:"bytes,6,opt,name=preferred_asset,json=preferredAsset,proto3" json:"preferred_asset"`
	Owner             github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,7,opt,name=owner,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"owner,omitempty"`
	Signer            github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,8,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
	AffiliateBps      github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,9,opt,name=affiliate_bps,json=affiliateBps,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"affiliate_bps"`
	SubaffiliateName  []string                                      `protobuf:"bytes,10,rep,name=subaffiliate_name,json=subaffiliateName,proto3" json:"subaffiliate_name,omitempty"`
	SubaffiliateBps   []github_com_cosmos_cosmos_sdk_types.Uint     `protobuf:"bytes,11,rep,name=subaffiliate_bps,json=subaffiliateBps,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"subaffiliate_bps"`
}

func (m *MsgManageMAYAName) Reset()         { *m = MsgManageMAYAName{} }
func (m *MsgManageMAYAName) String() string { return proto.CompactTextString(m) }
func (*MsgManageMAYAName) ProtoMessage()    {}
func (*MsgManageMAYAName) Descriptor() ([]byte, []int) {
	return fileDescriptor_78422a39e70c095a, []int{0}
}
func (m *MsgManageMAYAName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgManageMAYAName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgManageMAYAName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgManageMAYAName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgManageMAYAName.Merge(m, src)
}
func (m *MsgManageMAYAName) XXX_Size() int {
	return m.Size()
}
func (m *MsgManageMAYAName) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgManageMAYAName.DiscardUnknown(m)
}

var xxx_messageInfo_MsgManageMAYAName proto.InternalMessageInfo

func (m *MsgManageMAYAName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgManageMAYAName) GetChain() gitlab_com_mayachain_mayanode_common.Chain {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *MsgManageMAYAName) GetAddress() gitlab_com_mayachain_mayanode_common.Address {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgManageMAYAName) GetCoin() common.Coin {
	if m != nil {
		return m.Coin
	}
	return common.Coin{}
}

func (m *MsgManageMAYAName) GetExpireBlockHeight() int64 {
	if m != nil {
		return m.ExpireBlockHeight
	}
	return 0
}

func (m *MsgManageMAYAName) GetPreferredAsset() common.Asset {
	if m != nil {
		return m.PreferredAsset
	}
	return common.Asset{}
}

func (m *MsgManageMAYAName) GetOwner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *MsgManageMAYAName) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *MsgManageMAYAName) GetSubaffiliateName() []string {
	if m != nil {
		return m.SubaffiliateName
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgManageMAYAName)(nil), "types.MsgManageMAYAName")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/msg_manage_mayaname.proto", fileDescriptor_78422a39e70c095a)
}

var fileDescriptor_78422a39e70c095a = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x86, 0x1b, 0xda, 0x74, 0xd4, 0xeb, 0x18, 0x35, 0x1c, 0xa2, 0x1d, 0x92, 0x88, 0x03, 0x44,
	0xc0, 0x12, 0x06, 0x17, 0x0e, 0x5c, 0x12, 0x90, 0x60, 0x48, 0xe5, 0x10, 0xc1, 0x81, 0x5d, 0x22,
	0x27, 0x71, 0x5d, 0x6b, 0x75, 0x1c, 0xc5, 0x19, 0x6c, 0xff, 0x82, 0xdf, 0xc4, 0x69, 0xc7, 0x1d,
	0x11, 0x87, 0x08, 0xb5, 0xff, 0xa2, 0x27, 0x64, 0x3b, 0xd9, 0x3a, 0x21, 0xa1, 0xc1, 0xc9, 0xee,
	0xfb, 0x7e, 0x7e, 0xde, 0xcf, 0xcd, 0x67, 0xf0, 0x92, 0xa1, 0x33, 0x94, 0xcd, 0x11, 0x2d, 0x82,
	0x2f, 0x07, 0xc1, 0x69, 0x70, 0xf5, 0xb3, 0x3e, 0x2b, 0xb1, 0x08, 0x98, 0x20, 0x09, 0x43, 0x05,
	0x22, 0x38, 0x91, 0x56, 0x81, 0x18, 0xf6, 0xcb, 0x8a, 0xd7, 0x1c, 0x9a, 0xaa, 0x60, 0xcf, 0xbd,
	0x06, 0xc8, 0x38, 0x63, 0xbc, 0x68, 0x17, 0x5d, 0xb8, 0x77, 0x9f, 0x70, 0xc2, 0xd5, 0x36, 0x90,
	0x3b, 0xad, 0x3e, 0xf8, 0x6e, 0x82, 0xc9, 0x54, 0x90, 0xa9, 0x62, 0x4f, 0xc3, 0xcf, 0xe1, 0x07,
	0xc4, 0x30, 0x84, 0x60, 0x20, 0x23, 0x2c, 0xc3, 0x35, 0xbc, 0x51, 0xac, 0xf6, 0xf0, 0x0d, 0x30,
	0x15, 0xdf, 0xba, 0x25, 0xc5, 0xc8, 0x5f, 0x37, 0xce, 0x63, 0x42, 0xeb, 0x05, 0x4a, 0xfd, 0x8c,
	0xb3, 0x8d, 0x8e, 0x55, 0x83, 0x3c, 0xc7, 0x5d, 0xfc, 0x6b, 0xa9, 0xc6, 0xfa, 0x30, 0x7c, 0x0f,
	0xb6, 0x50, 0x9e, 0x57, 0x58, 0x08, 0xab, 0xaf, 0x38, 0xcf, 0xd6, 0x8d, 0xf3, 0xf4, 0x46, 0x9c,
	0x50, 0x9f, 0x8b, 0x3b, 0x00, 0x7c, 0x08, 0x06, 0x19, 0xa7, 0x85, 0x35, 0x70, 0x0d, 0x6f, 0xfb,
	0xf9, 0xd8, 0xef, 0xf2, 0x38, 0x2d, 0xa2, 0xc1, 0x79, 0xe3, 0xf4, 0x62, 0xe5, 0x43, 0x1f, 0xdc,
	0xc3, 0xa7, 0x25, 0xad, 0x70, 0x92, 0x2e, 0x78, 0x76, 0x9c, 0xcc, 0x31, 0x25, 0xf3, 0xda, 0x32,
	0x5d, 0xc3, 0xeb, 0xc7, 0x13, 0x6d, 0x45, 0xd2, 0x79, 0xa7, 0x0c, 0xf8, 0x0a, 0xec, 0x96, 0x15,
	0x9e, 0xe1, 0xaa, 0xc2, 0x79, 0x82, 0x84, 0xc0, 0xb5, 0x35, 0x54, 0x11, 0x3b, 0x5d, 0x44, 0x28,
	0xc5, 0x36, 0xe3, 0xce, 0x65, 0xad, 0x52, 0xe1, 0x5b, 0x60, 0xf2, 0xaf, 0x05, 0xae, 0xac, 0x2d,
	0xd7, 0xf0, 0xc6, 0xd1, 0xc1, 0xba, 0x71, 0xf6, 0x09, 0xad, 0xe7, 0x27, 0xfa, 0x7e, 0x19, 0x17,
	0x8c, 0x8b, 0x76, 0xd9, 0x17, 0xf9, 0xb1, 0xfe, 0xc2, 0x7e, 0x98, 0x65, 0xdd, 0x05, 0xf5, 0x79,
	0x78, 0x08, 0x86, 0x82, 0x12, 0x49, 0xba, 0xfd, 0xbf, 0xa4, 0x16, 0x00, 0x3f, 0x82, 0x1d, 0x34,
	0x9b, 0xd1, 0x05, 0x45, 0x35, 0x4e, 0xd2, 0x52, 0x58, 0x23, 0xf5, 0xdf, 0x07, 0xf2, 0x02, 0x3f,
	0x1b, 0xe7, 0xd1, 0x0d, 0xa8, 0x9f, 0x68, 0x51, 0xc7, 0xe3, 0x4b, 0x4a, 0x54, 0x0a, 0xf8, 0x04,
	0x4c, 0xc4, 0x49, 0x7a, 0x05, 0x56, 0x23, 0x03, 0xdc, 0xbe, 0x37, 0x8a, 0xef, 0x6e, 0x1a, 0x6a,
	0xa4, 0x8e, 0xc0, 0x35, 0x4d, 0x75, 0xb1, 0x2d, 0x6b, 0xff, 0xbd, 0x8b, 0xdd, 0x4d, 0x50, 0x54,
	0x8a, 0xe8, 0xf0, 0x7c, 0x69, 0x1b, 0x17, 0x4b, 0xdb, 0xf8, 0xb5, 0xb4, 0x8d, 0x6f, 0x2b, 0xbb,
	0x77, 0xb1, 0xb2, 0x7b, 0x3f, 0x56, 0x76, 0xef, 0x28, 0xf8, 0xfb, 0x64, 0xfd, 0xf1, 0xd0, 0xd2,
	0xa1, 0x7a, 0x16, 0x2f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x37, 0x9b, 0xc2, 0x91, 0x03,
	0x00, 0x00,
}

func (m *MsgManageMAYAName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgManageMAYAName) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgManageMAYAName) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SubaffiliateBps) > 0 {
		for iNdEx := len(m.SubaffiliateBps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.SubaffiliateBps[iNdEx].Size()
				i -= size
				if _, err := m.SubaffiliateBps[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintMsgManageMayaname(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.SubaffiliateName) > 0 {
		for iNdEx := len(m.SubaffiliateName) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SubaffiliateName[iNdEx])
			copy(dAtA[i:], m.SubaffiliateName[iNdEx])
			i = encodeVarintMsgManageMayaname(dAtA, i, uint64(len(m.SubaffiliateName[iNdEx])))
			i--
			dAtA[i] = 0x52
		}
	}
	{
		size := m.AffiliateBps.Size()
		i -= size
		if _, err := m.AffiliateBps.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgManageMayaname(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgManageMayaname(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintMsgManageMayaname(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size, err := m.PreferredAsset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgManageMayaname(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.ExpireBlockHeight != 0 {
		i = encodeVarintMsgManageMayaname(dAtA, i, uint64(m.ExpireBlockHeight))
		i--
		dAtA[i] = 0x28
	}
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgManageMayaname(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMsgManageMayaname(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintMsgManageMayaname(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMsgManageMayaname(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgManageMayaname(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgManageMayaname(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgManageMAYAName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMsgManageMayaname(uint64(l))
	}
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovMsgManageMayaname(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMsgManageMayaname(uint64(l))
	}
	l = m.Coin.Size()
	n += 1 + l + sovMsgManageMayaname(uint64(l))
	if m.ExpireBlockHeight != 0 {
		n += 1 + sovMsgManageMayaname(uint64(m.ExpireBlockHeight))
	}
	l = m.PreferredAsset.Size()
	n += 1 + l + sovMsgManageMayaname(uint64(l))
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovMsgManageMayaname(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgManageMayaname(uint64(l))
	}
	l = m.AffiliateBps.Size()
	n += 1 + l + sovMsgManageMayaname(uint64(l))
	if len(m.SubaffiliateName) > 0 {
		for _, s := range m.SubaffiliateName {
			l = len(s)
			n += 1 + l + sovMsgManageMayaname(uint64(l))
		}
	}
	if len(m.SubaffiliateBps) > 0 {
		for _, e := range m.SubaffiliateBps {
			l = e.Size()
			n += 1 + l + sovMsgManageMayaname(uint64(l))
		}
	}
	return n
}

func sovMsgManageMayaname(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgManageMayaname(x uint64) (n int) {
	return sovMsgManageMayaname(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgManageMAYAName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgManageMayaname
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgManageMAYAName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgManageMAYAName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = gitlab_com_mayachain_mayanode_common.Chain(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = gitlab_com_mayachain_mayanode_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpireBlockHeight", wireType)
			}
			m.ExpireBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpireBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreferredAsset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PreferredAsset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AffiliateBps", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AffiliateBps.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaffiliateName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubaffiliateName = append(m.SubaffiliateName, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubaffiliateBps", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Uint
			m.SubaffiliateBps = append(m.SubaffiliateBps, v)
			if err := m.SubaffiliateBps[len(m.SubaffiliateBps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgManageMayaname(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgManageMayaname
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgManageMayaname(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgManageMayaname
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgManageMayaname
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgManageMayaname
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgManageMayaname
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgManageMayaname
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgManageMayaname        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgManageMayaname          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgManageMayaname = fmt.Errorf("proto: unexpected end of group")
)
