// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/msg_trade_account.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	common "gitlab.com/mayachain/mayanode/common"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgTradeAccountDeposit struct {
	Tx      common.Tx                                     `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx"`
	Asset   gitlab_com_mayachain_mayanode_common.Asset    `protobuf:"bytes,2,opt,name=asset,proto3,customtype=gitlab.com/mayachain/mayanode/common.Asset" json:"asset"`
	Amount  github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"amount"`
	Address github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,4,opt,name=address,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"address,omitempty"`
	Signer  github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,5,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
}

func (m *MsgTradeAccountDeposit) Reset()         { *m = MsgTradeAccountDeposit{} }
func (m *MsgTradeAccountDeposit) String() string { return proto.CompactTextString(m) }
func (*MsgTradeAccountDeposit) ProtoMessage()    {}
func (*MsgTradeAccountDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ffac6e85c6a9872, []int{0}
}
func (m *MsgTradeAccountDeposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTradeAccountDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTradeAccountDeposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTradeAccountDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTradeAccountDeposit.Merge(m, src)
}
func (m *MsgTradeAccountDeposit) XXX_Size() int {
	return m.Size()
}
func (m *MsgTradeAccountDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTradeAccountDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTradeAccountDeposit proto.InternalMessageInfo

func (m *MsgTradeAccountDeposit) GetTx() common.Tx {
	if m != nil {
		return m.Tx
	}
	return common.Tx{}
}

func (m *MsgTradeAccountDeposit) GetAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *MsgTradeAccountDeposit) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

type MsgTradeAccountWithdrawal struct {
	Tx           common.Tx                                     `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx"`
	Asset        gitlab_com_mayachain_mayanode_common.Asset    `protobuf:"bytes,2,opt,name=asset,proto3,customtype=gitlab.com/mayachain/mayanode/common.Asset" json:"asset"`
	Amount       github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"amount"`
	AssetAddress gitlab_com_mayachain_mayanode_common.Address  `protobuf:"bytes,4,opt,name=asset_address,json=assetAddress,proto3,casttype=gitlab.com/mayachain/mayanode/common.Address" json:"asset_address,omitempty"`
	Signer       github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,5,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
}

func (m *MsgTradeAccountWithdrawal) Reset()         { *m = MsgTradeAccountWithdrawal{} }
func (m *MsgTradeAccountWithdrawal) String() string { return proto.CompactTextString(m) }
func (*MsgTradeAccountWithdrawal) ProtoMessage()    {}
func (*MsgTradeAccountWithdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ffac6e85c6a9872, []int{1}
}
func (m *MsgTradeAccountWithdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTradeAccountWithdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTradeAccountWithdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTradeAccountWithdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTradeAccountWithdrawal.Merge(m, src)
}
func (m *MsgTradeAccountWithdrawal) XXX_Size() int {
	return m.Size()
}
func (m *MsgTradeAccountWithdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTradeAccountWithdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTradeAccountWithdrawal proto.InternalMessageInfo

func (m *MsgTradeAccountWithdrawal) GetTx() common.Tx {
	if m != nil {
		return m.Tx
	}
	return common.Tx{}
}

func (m *MsgTradeAccountWithdrawal) GetAssetAddress() gitlab_com_mayachain_mayanode_common.Address {
	if m != nil {
		return m.AssetAddress
	}
	return ""
}

func (m *MsgTradeAccountWithdrawal) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgTradeAccountDeposit)(nil), "types.MsgTradeAccountDeposit")
	proto.RegisterType((*MsgTradeAccountWithdrawal)(nil), "types.MsgTradeAccountWithdrawal")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/msg_trade_account.proto", fileDescriptor_5ffac6e85c6a9872)
}

var fileDescriptor_5ffac6e85c6a9872 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x93, 0x3f, 0x4b, 0xc3, 0x40,
	0x18, 0xc6, 0x93, 0xf4, 0x8f, 0xf4, 0x6c, 0x97, 0x20, 0x12, 0x3b, 0x24, 0xa1, 0x8b, 0x45, 0x6c,
	0xcf, 0x56, 0x70, 0x4f, 0x10, 0xa4, 0x88, 0x4b, 0x68, 0x29, 0xb8, 0x94, 0x6b, 0x12, 0xd2, 0x60,
	0x93, 0x2b, 0xb9, 0xab, 0xa6, 0xa3, 0xdf, 0xc0, 0x8f, 0xd5, 0xb1, 0xa3, 0x38, 0x04, 0x69, 0xbf,
	0x82, 0x53, 0x27, 0x49, 0xee, 0x8a, 0x55, 0x41, 0x8a, 0x38, 0x39, 0xdd, 0x9b, 0x7b, 0x9f, 0xe7,
	0xc7, 0x9b, 0xe7, 0x78, 0xc1, 0x45, 0x80, 0x66, 0xc8, 0x1e, 0x21, 0x3f, 0x84, 0xf7, 0x2d, 0x18,
	0xc3, 0x8f, 0x4f, 0x3a, 0x9b, 0xb8, 0x04, 0x06, 0xc4, 0x1b, 0xd0, 0x08, 0x39, 0xee, 0x00, 0xd9,
	0x36, 0x9e, 0x86, 0xb4, 0x39, 0x89, 0x30, 0xc5, 0x72, 0x21, 0x6b, 0x57, 0xf5, 0x4f, 0x76, 0x1b,
	0x07, 0x01, 0x0e, 0xf9, 0xc1, 0x84, 0xd5, 0x03, 0x0f, 0x7b, 0x38, 0x2b, 0x61, 0x5a, 0xb1, 0xdb,
	0xda, 0x9b, 0x04, 0x0e, 0x6f, 0x88, 0xd7, 0x4d, 0xc9, 0x06, 0x03, 0x5f, 0xba, 0x13, 0x4c, 0x7c,
	0x2a, 0xeb, 0x40, 0xa2, 0xb1, 0x22, 0xea, 0x62, 0x7d, 0xbf, 0x0d, 0x9a, 0x9c, 0xd5, 0x8d, 0xcd,
	0xfc, 0x3c, 0xd1, 0x04, 0x4b, 0xa2, 0xb1, 0xdc, 0x07, 0x05, 0x44, 0x88, 0x4b, 0x15, 0x29, 0x13,
	0x55, 0x36, 0x22, 0x23, 0xbd, 0x34, 0xdb, 0xa9, 0xee, 0x25, 0xd1, 0x4e, 0x3c, 0x9f, 0x8e, 0xd1,
	0x30, 0x6d, 0x6e, 0xfd, 0x55, 0x5a, 0x85, 0xd8, 0x71, 0xe1, 0xb6, 0xc7, 0x62, 0x3c, 0xf9, 0x0a,
	0x14, 0x51, 0x90, 0xce, 0xa2, 0xe4, 0x74, 0xb1, 0x5e, 0x32, 0x21, 0x47, 0x1d, 0x7b, 0x3e, 0x1d,
	0x4d, 0x19, 0xca, 0xc6, 0x24, 0xc0, 0x84, 0x1f, 0x0d, 0xe2, 0xdc, 0xb1, 0xa0, 0x9a, 0x3d, 0x3f,
	0xa4, 0x16, 0xb7, 0xcb, 0xd7, 0x60, 0x0f, 0x39, 0x4e, 0xe4, 0x12, 0xa2, 0xe4, 0x75, 0xb1, 0x5e,
	0x36, 0x5b, 0xeb, 0x44, 0x6b, 0xec, 0x40, 0x31, 0x6c, 0xdb, 0x60, 0x46, 0x6b, 0x43, 0x90, 0x3b,
	0xa0, 0x48, 0x7c, 0x2f, 0x74, 0x23, 0xa5, 0xf0, 0x5b, 0x16, 0x07, 0xd4, 0x1e, 0x73, 0xe0, 0xe8,
	0x4b, 0xec, 0x7d, 0x9f, 0x8e, 0x9c, 0x08, 0x3d, 0xa0, 0xf1, 0xbf, 0x48, 0xbe, 0x07, 0x2a, 0x19,
	0x71, 0xb0, 0x9d, 0x7f, 0xc9, 0x3c, 0x5b, 0x27, 0xda, 0xe9, 0x6e, 0x63, 0xf1, 0xc8, 0xca, 0x19,
	0xc6, 0xf8, 0xf3, 0x37, 0x30, 0x3b, 0xf3, 0xa5, 0x2a, 0x2e, 0x96, 0xaa, 0xf8, 0xba, 0x54, 0xc5,
	0xa7, 0x95, 0x2a, 0x2c, 0x56, 0xaa, 0xf0, 0xbc, 0x52, 0x85, 0x5b, 0xf8, 0xf3, 0x80, 0xdf, 0x96,
	0x73, 0x58, 0xcc, 0x96, 0xe9, 0xfc, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x55, 0x41, 0x40, 0x73, 0xc5,
	0x03, 0x00, 0x00,
}

func (m *MsgTradeAccountDeposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTradeAccountDeposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTradeAccountDeposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Asset.Size()
		i -= size
		if _, err := m.Asset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MsgTradeAccountWithdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTradeAccountWithdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTradeAccountWithdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AssetAddress) > 0 {
		i -= len(m.AssetAddress)
		copy(dAtA[i:], m.AssetAddress)
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(len(m.AssetAddress)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Asset.Size()
		i -= size
		if _, err := m.Asset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMsgTradeAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgTradeAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgTradeAccountDeposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Tx.Size()
	n += 1 + l + sovMsgTradeAccount(uint64(l))
	l = m.Asset.Size()
	n += 1 + l + sovMsgTradeAccount(uint64(l))
	l = m.Amount.Size()
	n += 1 + l + sovMsgTradeAccount(uint64(l))
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMsgTradeAccount(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgTradeAccount(uint64(l))
	}
	return n
}

func (m *MsgTradeAccountWithdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Tx.Size()
	n += 1 + l + sovMsgTradeAccount(uint64(l))
	l = m.Asset.Size()
	n += 1 + l + sovMsgTradeAccount(uint64(l))
	l = m.Amount.Size()
	n += 1 + l + sovMsgTradeAccount(uint64(l))
	l = len(m.AssetAddress)
	if l > 0 {
		n += 1 + l + sovMsgTradeAccount(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgTradeAccount(uint64(l))
	}
	return n
}

func sovMsgTradeAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgTradeAccount(x uint64) (n int) {
	return sovMsgTradeAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgTradeAccountDeposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgTradeAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTradeAccountDeposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTradeAccountDeposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgTradeAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTradeAccountWithdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgTradeAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTradeAccountWithdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTradeAccountWithdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetAddress = gitlab_com_mayachain_mayanode_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgTradeAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgTradeAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgTradeAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgTradeAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgTradeAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgTradeAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgTradeAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgTradeAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgTradeAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgTradeAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgTradeAccount = fmt.Errorf("proto: unexpected end of group")
)
