// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/msg_cacao_pool.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	common "gitlab.com/mayachain/mayanode/common"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCacaoPoolDeposit struct {
	Signer github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
	Tx     common.Tx                                     `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx"`
}

func (m *MsgCacaoPoolDeposit) Reset()         { *m = MsgCacaoPoolDeposit{} }
func (m *MsgCacaoPoolDeposit) String() string { return proto.CompactTextString(m) }
func (*MsgCacaoPoolDeposit) ProtoMessage()    {}
func (*MsgCacaoPoolDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c0e32eaec62fdd6, []int{0}
}
func (m *MsgCacaoPoolDeposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCacaoPoolDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCacaoPoolDeposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCacaoPoolDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCacaoPoolDeposit.Merge(m, src)
}
func (m *MsgCacaoPoolDeposit) XXX_Size() int {
	return m.Size()
}
func (m *MsgCacaoPoolDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCacaoPoolDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCacaoPoolDeposit proto.InternalMessageInfo

func (m *MsgCacaoPoolDeposit) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *MsgCacaoPoolDeposit) GetTx() common.Tx {
	if m != nil {
		return m.Tx
	}
	return common.Tx{}
}

type MsgCacaoPoolWithdraw struct {
	Signer               github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
	Tx                   common.Tx                                     `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx"`
	BasisPoints          github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,3,opt,name=basis_points,json=basisPoints,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"basis_points"`
	AffiliateAddress     gitlab_com_mayachain_mayanode_common.Address  `protobuf:"bytes,4,opt,name=affiliate_address,json=affiliateAddress,proto3,casttype=gitlab.com/mayachain/mayanode/common.Address" json:"affiliate_address,omitempty"` // Deprecated: Do not use.
	AffiliateBasisPoints github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,5,opt,name=affiliate_basis_points,json=affiliateBasisPoints,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"affiliate_basis_points"`
}

func (m *MsgCacaoPoolWithdraw) Reset()         { *m = MsgCacaoPoolWithdraw{} }
func (m *MsgCacaoPoolWithdraw) String() string { return proto.CompactTextString(m) }
func (*MsgCacaoPoolWithdraw) ProtoMessage()    {}
func (*MsgCacaoPoolWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c0e32eaec62fdd6, []int{1}
}
func (m *MsgCacaoPoolWithdraw) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCacaoPoolWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCacaoPoolWithdraw.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCacaoPoolWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCacaoPoolWithdraw.Merge(m, src)
}
func (m *MsgCacaoPoolWithdraw) XXX_Size() int {
	return m.Size()
}
func (m *MsgCacaoPoolWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCacaoPoolWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCacaoPoolWithdraw proto.InternalMessageInfo

func (m *MsgCacaoPoolWithdraw) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *MsgCacaoPoolWithdraw) GetTx() common.Tx {
	if m != nil {
		return m.Tx
	}
	return common.Tx{}
}

// Deprecated: Do not use.
func (m *MsgCacaoPoolWithdraw) GetAffiliateAddress() gitlab_com_mayachain_mayanode_common.Address {
	if m != nil {
		return m.AffiliateAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgCacaoPoolDeposit)(nil), "types.MsgCacaoPoolDeposit")
	proto.RegisterType((*MsgCacaoPoolWithdraw)(nil), "types.MsgCacaoPoolWithdraw")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/msg_cacao_pool.proto", fileDescriptor_0c0e32eaec62fdd6)
}

var fileDescriptor_0c0e32eaec62fdd6 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xcd, 0xaa, 0xd3, 0x40,
	0x14, 0x80, 0x33, 0xfd, 0x03, 0xa7, 0x5d, 0x68, 0x2c, 0x12, 0xba, 0x48, 0x42, 0x37, 0x76, 0x61,
	0x33, 0xb4, 0x7d, 0x82, 0x46, 0x37, 0x5d, 0x08, 0x25, 0x28, 0x82, 0x9b, 0x30, 0x9d, 0xa4, 0xe9,
	0x60, 0x92, 0x13, 0x32, 0xa3, 0xa6, 0x5b, 0x9f, 0xc0, 0x37, 0xf0, 0x75, 0xba, 0xec, 0x52, 0x5c,
	0x04, 0x69, 0xdf, 0xa2, 0x2b, 0xc9, 0x8f, 0x8d, 0x45, 0xb8, 0x5c, 0xee, 0xe2, 0xae, 0xe6, 0x64,
	0x4e, 0xe6, 0x3b, 0xdf, 0xe1, 0x1c, 0xbc, 0x88, 0xe8, 0x9e, 0xb2, 0x1d, 0xe5, 0x31, 0xf9, 0x32,
	0x23, 0x19, 0x69, 0x3e, 0xe5, 0x3e, 0xf1, 0x05, 0x89, 0x44, 0xe0, 0x32, 0xca, 0x28, 0xb8, 0x09,
	0x40, 0x68, 0x25, 0x29, 0x48, 0x50, 0xbb, 0x65, 0x6e, 0x64, 0xde, 0xbc, 0x65, 0x10, 0x45, 0x10,
	0xd7, 0x47, 0xf5, 0xe3, 0x68, 0x18, 0x40, 0x00, 0x65, 0x48, 0x8a, 0xa8, 0xba, 0x1d, 0x7f, 0x43,
	0xf8, 0xf9, 0x5b, 0x11, 0xbc, 0x2e, 0xb0, 0x6b, 0x80, 0xf0, 0x8d, 0x9f, 0x80, 0xe0, 0x52, 0x5d,
	0xe1, 0x9e, 0xe0, 0x41, 0xec, 0xa7, 0x1a, 0x32, 0xd1, 0x64, 0x60, 0xcf, 0x2e, 0xb9, 0x31, 0x0d,
	0xb8, 0xdc, 0x7d, 0xde, 0x58, 0x0c, 0x22, 0xc2, 0x40, 0x44, 0x20, 0xea, 0x63, 0x2a, 0xbc, 0x4f,
	0x95, 0xa3, 0xb5, 0x64, 0x6c, 0xe9, 0x79, 0xa9, 0x2f, 0x84, 0x53, 0x03, 0x54, 0x13, 0xb7, 0x64,
	0xa6, 0xb5, 0x4c, 0x34, 0xe9, 0xcf, 0xb1, 0x55, 0x3b, 0xbd, 0xcb, 0xec, 0xce, 0x21, 0x37, 0x14,
	0xa7, 0x25, 0xb3, 0xf1, 0x8f, 0x36, 0x1e, 0xfe, 0x2b, 0xf1, 0x81, 0xcb, 0x9d, 0x97, 0xd2, 0xaf,
	0x8f, 0x6a, 0xa1, 0x3a, 0x78, 0xb0, 0xa1, 0x82, 0x0b, 0x37, 0x01, 0x1e, 0x4b, 0xa1, 0xb5, 0x4d,
	0x34, 0x79, 0x62, 0x93, 0x22, 0xff, 0x2b, 0x37, 0x5e, 0xde, 0xa3, 0xec, 0x7b, 0x1e, 0x4b, 0xa7,
	0x5f, 0x42, 0xd6, 0x25, 0x43, 0x75, 0xf1, 0x33, 0xba, 0xdd, 0xf2, 0x90, 0x53, 0xe9, 0xbb, 0xb4,
	0x52, 0xd2, 0x3a, 0x25, 0x78, 0x7e, 0xc9, 0x8d, 0x57, 0x01, 0x97, 0x21, 0xad, 0xa0, 0xcd, 0x00,
	0x8b, 0x28, 0x06, 0xcf, 0xff, 0x3b, 0xbf, 0xba, 0x15, 0x0d, 0x39, 0x4f, 0xaf, 0xb0, 0xfa, 0x4e,
	0xf5, 0xf1, 0x8b, 0xa6, 0xc0, 0x8d, 0x7e, 0xf7, 0x61, 0xfa, 0xc3, 0x2b, 0xce, 0x6e, 0xfa, 0xb0,
	0x57, 0x87, 0x93, 0x8e, 0x8e, 0x27, 0x1d, 0xfd, 0x3e, 0xe9, 0xe8, 0xfb, 0x59, 0x57, 0x8e, 0x67,
	0x5d, 0xf9, 0x79, 0xd6, 0x95, 0x8f, 0xe4, 0xee, 0x16, 0xfe, 0xdb, 0xe2, 0x4d, 0xaf, 0x5c, 0xbc,
	0xc5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x44, 0xc7, 0x8e, 0xee, 0x02, 0x00, 0x00,
}

func (m *MsgCacaoPoolDeposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCacaoPoolDeposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCacaoPoolDeposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgCacaoPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgCacaoPool(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCacaoPoolWithdraw) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCacaoPoolWithdraw) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCacaoPoolWithdraw) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AffiliateBasisPoints.Size()
		i -= size
		if _, err := m.AffiliateBasisPoints.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgCacaoPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.AffiliateAddress) > 0 {
		i -= len(m.AffiliateAddress)
		copy(dAtA[i:], m.AffiliateAddress)
		i = encodeVarintMsgCacaoPool(dAtA, i, uint64(len(m.AffiliateAddress)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.BasisPoints.Size()
		i -= size
		if _, err := m.BasisPoints.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgCacaoPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgCacaoPool(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgCacaoPool(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMsgCacaoPool(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgCacaoPool(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCacaoPoolDeposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgCacaoPool(uint64(l))
	}
	l = m.Tx.Size()
	n += 1 + l + sovMsgCacaoPool(uint64(l))
	return n
}

func (m *MsgCacaoPoolWithdraw) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgCacaoPool(uint64(l))
	}
	l = m.Tx.Size()
	n += 1 + l + sovMsgCacaoPool(uint64(l))
	l = m.BasisPoints.Size()
	n += 1 + l + sovMsgCacaoPool(uint64(l))
	l = len(m.AffiliateAddress)
	if l > 0 {
		n += 1 + l + sovMsgCacaoPool(uint64(l))
	}
	l = m.AffiliateBasisPoints.Size()
	n += 1 + l + sovMsgCacaoPool(uint64(l))
	return n
}

func sovMsgCacaoPool(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgCacaoPool(x uint64) (n int) {
	return sovMsgCacaoPool(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCacaoPoolDeposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgCacaoPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCacaoPoolDeposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCacaoPoolDeposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgCacaoPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgCacaoPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgCacaoPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCacaoPoolWithdraw) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgCacaoPool
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCacaoPoolWithdraw: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCacaoPoolWithdraw: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgCacaoPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgCacaoPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasisPoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgCacaoPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BasisPoints.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AffiliateAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgCacaoPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AffiliateAddress = gitlab_com_mayachain_mayanode_common.Address(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AffiliateBasisPoints", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgCacaoPool
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AffiliateBasisPoints.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgCacaoPool(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgCacaoPool
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgCacaoPool(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgCacaoPool
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgCacaoPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgCacaoPool
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgCacaoPool
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgCacaoPool
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgCacaoPool
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgCacaoPool        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgCacaoPool          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgCacaoPool = fmt.Errorf("proto: unexpected end of group")
)
