// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/type_cacao_provider.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CACAOProvider struct {
	CacaoAddress       github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=cacao_address,json=cacaoAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"cacao_address,omitempty"`
	DepositAmount      github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,2,opt,name=deposit_amount,json=depositAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"deposit_amount"`
	WithdrawAmount     github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,3,opt,name=withdraw_amount,json=withdrawAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"withdraw_amount"`
	Units              github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,4,opt,name=units,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"units"`
	LastDepositHeight  int64                                         `protobuf:"varint,5,opt,name=last_deposit_height,json=lastDepositHeight,proto3" json:"last_deposit_height,omitempty"`
	LastWithdrawHeight int64                                         `protobuf:"varint,6,opt,name=last_withdraw_height,json=lastWithdrawHeight,proto3" json:"last_withdraw_height,omitempty"`
}

func (m *CACAOProvider) Reset()         { *m = CACAOProvider{} }
func (m *CACAOProvider) String() string { return proto.CompactTextString(m) }
func (*CACAOProvider) ProtoMessage()    {}
func (*CACAOProvider) Descriptor() ([]byte, []int) {
	return fileDescriptor_4243b0235f0f23d0, []int{0}
}
func (m *CACAOProvider) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CACAOProvider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CACAOProvider.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CACAOProvider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CACAOProvider.Merge(m, src)
}
func (m *CACAOProvider) XXX_Size() int {
	return m.Size()
}
func (m *CACAOProvider) XXX_DiscardUnknown() {
	xxx_messageInfo_CACAOProvider.DiscardUnknown(m)
}

var xxx_messageInfo_CACAOProvider proto.InternalMessageInfo

func (m *CACAOProvider) GetCacaoAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.CacaoAddress
	}
	return nil
}

func (m *CACAOProvider) GetLastDepositHeight() int64 {
	if m != nil {
		return m.LastDepositHeight
	}
	return 0
}

func (m *CACAOProvider) GetLastWithdrawHeight() int64 {
	if m != nil {
		return m.LastWithdrawHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*CACAOProvider)(nil), "types.CACAOProvider")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/type_cacao_provider.proto", fileDescriptor_4243b0235f0f23d0)
}

var fileDescriptor_4243b0235f0f23d0 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x31, 0x4f, 0xf2, 0x40,
	0x18, 0xc7, 0xdb, 0x97, 0x17, 0x92, 0xf7, 0x02, 0xbc, 0xf1, 0x64, 0x68, 0x1c, 0x0a, 0x71, 0x91,
	0x85, 0x9e, 0xc4, 0xc5, 0xb5, 0xa0, 0x89, 0x4e, 0x1a, 0x12, 0xd1, 0xb8, 0x34, 0xc7, 0x5d, 0xd3,
	0x5e, 0xa4, 0xbd, 0xa6, 0x77, 0x80, 0x7c, 0x0b, 0x3f, 0x93, 0x13, 0x23, 0xa3, 0x71, 0x20, 0x06,
	0xbe, 0x85, 0x93, 0xe9, 0xdd, 0x21, 0x83, 0x8b, 0x61, 0x69, 0x9f, 0xe7, 0xfe, 0xcf, 0xff, 0x97,
	0xe7, 0x49, 0xfe, 0xe0, 0x3c, 0xc1, 0x73, 0x4c, 0x62, 0xcc, 0x52, 0x34, 0xed, 0xa2, 0x67, 0xb4,
	0x6b, 0xe5, 0x3c, 0x0b, 0x85, 0xfa, 0x06, 0x04, 0x13, 0xcc, 0x83, 0x2c, 0xe7, 0x53, 0x46, 0xc3,
	0xdc, 0xcb, 0x72, 0x2e, 0x39, 0x2c, 0xab, 0x81, 0xa3, 0x46, 0xc4, 0x23, 0xae, 0x5e, 0x50, 0x51,
	0x69, 0xf1, 0xf8, 0xb5, 0x04, 0x6a, 0x7d, 0xbf, 0xef, 0xdf, 0xdc, 0x1a, 0x13, 0x1c, 0x82, 0x9a,
	0xc6, 0x60, 0x4a, 0xf3, 0x50, 0x08, 0xc7, 0x6e, 0xd9, 0xed, 0x6a, 0xaf, 0xfb, 0xb9, 0x6a, 0x76,
	0x22, 0x26, 0xe3, 0xc9, 0xc8, 0x23, 0x3c, 0x41, 0x84, 0x8b, 0x84, 0x0b, 0xf3, 0xeb, 0x08, 0xfa,
	0xa4, 0xf7, 0xf0, 0x7c, 0x42, 0x7c, 0x6d, 0x1c, 0x54, 0x15, 0xc7, 0x74, 0x70, 0x08, 0xea, 0x34,
	0xcc, 0xb8, 0x60, 0x32, 0xc0, 0x09, 0x9f, 0xa4, 0xd2, 0xf9, 0xd3, 0xb2, 0xdb, 0xff, 0x7a, 0x68,
	0xb1, 0x6a, 0x5a, 0xef, 0xab, 0xe6, 0xc9, 0x2f, 0xe0, 0x77, 0x2c, 0x95, 0x83, 0x9a, 0xc1, 0xf8,
	0x8a, 0x02, 0x1f, 0xc0, 0xff, 0x19, 0x93, 0x31, 0xcd, 0xf1, 0x6c, 0x0b, 0x2e, 0xed, 0x07, 0xae,
	0x6f, 0x39, 0x86, 0x7c, 0x09, 0xca, 0x93, 0x94, 0x49, 0xe1, 0xfc, 0xdd, 0x8f, 0xa7, 0xdd, 0xd0,
	0x03, 0x87, 0x63, 0x2c, 0x64, 0xb0, 0xbd, 0x3e, 0x0e, 0x59, 0x14, 0x4b, 0xa7, 0xdc, 0xb2, 0xdb,
	0xa5, 0xc1, 0x41, 0x21, 0x5d, 0x68, 0xe5, 0x4a, 0x09, 0xf0, 0x14, 0x34, 0xd4, 0xfc, 0xf7, 0x55,
	0xc6, 0x50, 0x51, 0x06, 0x58, 0x68, 0xf7, 0x46, 0xd2, 0x8e, 0xde, 0xf5, 0x62, 0xed, 0xda, 0xcb,
	0xb5, 0x6b, 0x7f, 0xac, 0x5d, 0xfb, 0x65, 0xe3, 0x5a, 0xcb, 0x8d, 0x6b, 0xbd, 0x6d, 0x5c, 0xeb,
	0x11, 0x45, 0x4c, 0x8e, 0xb1, 0xde, 0x75, 0x97, 0x98, 0xa2, 0x4a, 0x39, 0x0d, 0x7f, 0xc6, 0x68,
	0x54, 0x51, 0xb1, 0x38, 0xfb, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x44, 0x03, 0xc4, 0x65, 0x6f, 0x02,
	0x00, 0x00,
}

func (m *CACAOProvider) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CACAOProvider) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CACAOProvider) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastWithdrawHeight != 0 {
		i = encodeVarintTypeCacaoProvider(dAtA, i, uint64(m.LastWithdrawHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.LastDepositHeight != 0 {
		i = encodeVarintTypeCacaoProvider(dAtA, i, uint64(m.LastDepositHeight))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Units.Size()
		i -= size
		if _, err := m.Units.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeCacaoProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.WithdrawAmount.Size()
		i -= size
		if _, err := m.WithdrawAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeCacaoProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.DepositAmount.Size()
		i -= size
		if _, err := m.DepositAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeCacaoProvider(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.CacaoAddress) > 0 {
		i -= len(m.CacaoAddress)
		copy(dAtA[i:], m.CacaoAddress)
		i = encodeVarintTypeCacaoProvider(dAtA, i, uint64(len(m.CacaoAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypeCacaoProvider(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeCacaoProvider(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CACAOProvider) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CacaoAddress)
	if l > 0 {
		n += 1 + l + sovTypeCacaoProvider(uint64(l))
	}
	l = m.DepositAmount.Size()
	n += 1 + l + sovTypeCacaoProvider(uint64(l))
	l = m.WithdrawAmount.Size()
	n += 1 + l + sovTypeCacaoProvider(uint64(l))
	l = m.Units.Size()
	n += 1 + l + sovTypeCacaoProvider(uint64(l))
	if m.LastDepositHeight != 0 {
		n += 1 + sovTypeCacaoProvider(uint64(m.LastDepositHeight))
	}
	if m.LastWithdrawHeight != 0 {
		n += 1 + sovTypeCacaoProvider(uint64(m.LastWithdrawHeight))
	}
	return n
}

func sovTypeCacaoProvider(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeCacaoProvider(x uint64) (n int) {
	return sovTypeCacaoProvider(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CACAOProvider) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeCacaoProvider
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CACAOProvider: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CACAOProvider: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CacaoAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeCacaoProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CacaoAddress = append(m.CacaoAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.CacaoAddress == nil {
				m.CacaoAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeCacaoProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DepositAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeCacaoProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WithdrawAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Units", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeCacaoProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Units.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastDepositHeight", wireType)
			}
			m.LastDepositHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeCacaoProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastDepositHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastWithdrawHeight", wireType)
			}
			m.LastWithdrawHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeCacaoProvider
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastWithdrawHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypeCacaoProvider(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypeCacaoProvider
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeCacaoProvider(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeCacaoProvider
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeCacaoProvider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeCacaoProvider
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeCacaoProvider
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeCacaoProvider
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeCacaoProvider
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeCacaoProvider        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeCacaoProvider          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeCacaoProvider = fmt.Errorf("proto: unexpected end of group")
)
