// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mayachain/v1/x/mayachain/types/type_trade_account.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "gitlab.com/mayachain/mayanode/common"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TradeAccount struct {
	Asset              gitlab_com_mayachain_mayanode_common.Asset    `protobuf:"bytes,1,opt,name=asset,proto3,customtype=gitlab.com/mayachain/mayanode/common.Asset" json:"asset"`
	Units              github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,2,opt,name=units,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"units"`
	Owner              github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,3,opt,name=owner,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"owner,omitempty"`
	LastAddHeight      int64                                         `protobuf:"varint,4,opt,name=last_add_height,json=lastAddHeight,proto3" json:"last_add_height,omitempty"`
	LastWithdrawHeight int64                                         `protobuf:"varint,5,opt,name=last_withdraw_height,json=lastWithdrawHeight,proto3" json:"last_withdraw_height,omitempty"`
}

func (m *TradeAccount) Reset()         { *m = TradeAccount{} }
func (m *TradeAccount) String() string { return proto.CompactTextString(m) }
func (*TradeAccount) ProtoMessage()    {}
func (*TradeAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a57560fd814e23, []int{0}
}
func (m *TradeAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TradeAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TradeAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TradeAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeAccount.Merge(m, src)
}
func (m *TradeAccount) XXX_Size() int {
	return m.Size()
}
func (m *TradeAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeAccount.DiscardUnknown(m)
}

var xxx_messageInfo_TradeAccount proto.InternalMessageInfo

func (m *TradeAccount) GetOwner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *TradeAccount) GetLastAddHeight() int64 {
	if m != nil {
		return m.LastAddHeight
	}
	return 0
}

func (m *TradeAccount) GetLastWithdrawHeight() int64 {
	if m != nil {
		return m.LastWithdrawHeight
	}
	return 0
}

type TradeUnit struct {
	Asset gitlab_com_mayachain_mayanode_common.Asset `protobuf:"bytes,1,opt,name=asset,proto3,customtype=gitlab.com/mayachain/mayanode/common.Asset" json:"asset"`
	Units github_com_cosmos_cosmos_sdk_types.Uint    `protobuf:"bytes,2,opt,name=units,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"units"`
	Depth github_com_cosmos_cosmos_sdk_types.Uint    `protobuf:"bytes,3,opt,name=depth,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"depth"`
}

func (m *TradeUnit) Reset()         { *m = TradeUnit{} }
func (m *TradeUnit) String() string { return proto.CompactTextString(m) }
func (*TradeUnit) ProtoMessage()    {}
func (*TradeUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a57560fd814e23, []int{1}
}
func (m *TradeUnit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TradeUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TradeUnit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TradeUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeUnit.Merge(m, src)
}
func (m *TradeUnit) XXX_Size() int {
	return m.Size()
}
func (m *TradeUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeUnit.DiscardUnknown(m)
}

var xxx_messageInfo_TradeUnit proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TradeAccount)(nil), "types.TradeAccount")
	proto.RegisterType((*TradeUnit)(nil), "types.TradeUnit")
}

func init() {
	proto.RegisterFile("mayachain/v1/x/mayachain/types/type_trade_account.proto", fileDescriptor_46a57560fd814e23)
}

var fileDescriptor_46a57560fd814e23 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0x31, 0x6b, 0xe3, 0x30,
	0x14, 0xc7, 0xad, 0xe4, 0x7c, 0x10, 0x5d, 0xc2, 0x81, 0xc9, 0x60, 0x32, 0x38, 0x26, 0xc3, 0x9d,
	0x39, 0x48, 0x7c, 0xc9, 0x0d, 0x37, 0xdb, 0x10, 0xee, 0xba, 0x9a, 0x86, 0x40, 0x17, 0xa3, 0x58,
	0xc2, 0x16, 0x8d, 0xa5, 0x60, 0x29, 0x4d, 0xf3, 0x2d, 0xfa, 0xb1, 0x32, 0xa6, 0x5b, 0xe9, 0x10,
	0x4a, 0xf2, 0x0d, 0x3a, 0x76, 0x2a, 0x96, 0x5c, 0x9a, 0x52, 0x28, 0xa5, 0x53, 0x17, 0xeb, 0xf9,
	0xfd, 0xff, 0xff, 0x1f, 0xd2, 0xe3, 0xc1, 0xbf, 0x39, 0x5a, 0xa3, 0x24, 0x43, 0x94, 0xf9, 0x17,
	0x43, 0xff, 0xd2, 0x7f, 0xfe, 0x95, 0xeb, 0x05, 0x11, 0xea, 0x1b, 0xcb, 0x02, 0x61, 0x12, 0xa3,
	0x24, 0xe1, 0x4b, 0x26, 0x07, 0x8b, 0x82, 0x4b, 0x6e, 0x99, 0x4a, 0xef, 0xb8, 0x2f, 0xf2, 0x09,
	0xcf, 0x73, 0xce, 0xaa, 0x43, 0x1b, 0x3b, 0xed, 0x94, 0xa7, 0x5c, 0x95, 0x7e, 0x59, 0xe9, 0x6e,
	0xef, 0xba, 0x06, 0x9b, 0xa7, 0x25, 0x36, 0xd0, 0x54, 0x6b, 0x0a, 0x4d, 0x24, 0x04, 0x91, 0x36,
	0x70, 0x81, 0xf7, 0x6d, 0xd4, 0x1a, 0x54, 0x90, 0xa0, 0x6c, 0x86, 0xa3, 0xcd, 0xae, 0x6b, 0xdc,
	0xee, 0xba, 0xbf, 0x52, 0x2a, 0xe7, 0x68, 0x56, 0x8a, 0x47, 0x57, 0x2d, 0x2b, 0xc6, 0x31, 0xf1,
	0x8f, 0x33, 0x91, 0xe6, 0x59, 0x63, 0x68, 0x2e, 0x19, 0x95, 0xc2, 0xae, 0xb9, 0xc0, 0x6b, 0x84,
	0x7e, 0x45, 0xfa, 0x99, 0x52, 0x99, 0x2d, 0x35, 0x29, 0xe1, 0x22, 0xe7, 0xa2, 0x3a, 0xfa, 0x02,
	0x9f, 0xeb, 0xc7, 0x0f, 0x26, 0x94, 0xc9, 0x48, 0xa7, 0xad, 0x7f, 0xd0, 0xe4, 0x2b, 0x46, 0x0a,
	0xbb, 0xee, 0x02, 0xaf, 0x19, 0x0e, 0x1f, 0x76, 0xdd, 0xfe, 0x3b, 0x10, 0x41, 0x92, 0x04, 0x18,
	0x17, 0x44, 0x88, 0x48, 0xe7, 0xad, 0x1f, 0xf0, 0xfb, 0x1c, 0x09, 0x19, 0x23, 0x8c, 0xe3, 0x8c,
	0xd0, 0x34, 0x93, 0xf6, 0x17, 0x17, 0x78, 0xf5, 0xa8, 0x55, 0xb6, 0x03, 0x8c, 0xff, 0xab, 0xa6,
	0xf5, 0x1b, 0xb6, 0x95, 0x6f, 0x45, 0x65, 0x86, 0x0b, 0xb4, 0x7a, 0x32, 0x9b, 0xca, 0x6c, 0x95,
	0xda, 0xb4, 0x92, 0x74, 0xa2, 0x77, 0x0f, 0x60, 0x43, 0xcd, 0x74, 0xc2, 0xe8, 0xe7, 0x1f, 0xe8,
	0x18, 0x9a, 0x98, 0x2c, 0x64, 0xa6, 0x06, 0xfa, 0x11, 0x8c, 0x4a, 0x87, 0x27, 0x9b, 0xbd, 0x03,
	0xb6, 0x7b, 0x07, 0xdc, 0xed, 0x1d, 0x70, 0x75, 0x70, 0x8c, 0xed, 0xc1, 0x31, 0x6e, 0x0e, 0x8e,
	0x71, 0xe6, 0xbf, 0xfd, 0xb4, 0x57, 0xbb, 0x3e, 0xfb, 0xaa, 0x56, 0xf3, 0xcf, 0x63, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x85, 0xc4, 0x7b, 0x7a, 0x14, 0x03, 0x00, 0x00,
}

func (m *TradeAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TradeAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TradeAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastWithdrawHeight != 0 {
		i = encodeVarintTypeTradeAccount(dAtA, i, uint64(m.LastWithdrawHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.LastAddHeight != 0 {
		i = encodeVarintTypeTradeAccount(dAtA, i, uint64(m.LastAddHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTypeTradeAccount(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.Units.Size()
		i -= size
		if _, err := m.Units.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.Asset.Size()
		i -= size
		if _, err := m.Asset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *TradeUnit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TradeUnit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TradeUnit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Depth.Size()
		i -= size
		if _, err := m.Depth.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Units.Size()
		i -= size
		if _, err := m.Units.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.Asset.Size()
		i -= size
		if _, err := m.Asset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypeTradeAccount(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTypeTradeAccount(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypeTradeAccount(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TradeAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Asset.Size()
	n += 1 + l + sovTypeTradeAccount(uint64(l))
	l = m.Units.Size()
	n += 1 + l + sovTypeTradeAccount(uint64(l))
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTypeTradeAccount(uint64(l))
	}
	if m.LastAddHeight != 0 {
		n += 1 + sovTypeTradeAccount(uint64(m.LastAddHeight))
	}
	if m.LastWithdrawHeight != 0 {
		n += 1 + sovTypeTradeAccount(uint64(m.LastWithdrawHeight))
	}
	return n
}

func (m *TradeUnit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Asset.Size()
	n += 1 + l + sovTypeTradeAccount(uint64(l))
	l = m.Units.Size()
	n += 1 + l + sovTypeTradeAccount(uint64(l))
	l = m.Depth.Size()
	n += 1 + l + sovTypeTradeAccount(uint64(l))
	return n
}

func sovTypeTradeAccount(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypeTradeAccount(x uint64) (n int) {
	return sovTypeTradeAccount(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TradeAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeTradeAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TradeAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TradeAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Units", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Units.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastAddHeight", wireType)
			}
			m.LastAddHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastAddHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastWithdrawHeight", wireType)
			}
			m.LastWithdrawHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastWithdrawHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypeTradeAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TradeUnit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypeTradeAccount
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TradeUnit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TradeUnit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Units", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Units.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depth", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Depth.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypeTradeAccount(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTypeTradeAccount
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypeTradeAccount(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypeTradeAccount
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypeTradeAccount
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypeTradeAccount
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypeTradeAccount
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypeTradeAccount
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypeTradeAccount        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypeTradeAccount          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypeTradeAccount = fmt.Errorf("proto: unexpected end of group")
)
