// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: messages/join_party.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinPartyLeaderComm_ResponseType int32

const (
	JoinPartyLeaderComm_Unknown        JoinPartyLeaderComm_ResponseType = 0
	JoinPartyLeaderComm_Success        JoinPartyLeaderComm_ResponseType = 1
	JoinPartyLeaderComm_Timeout        JoinPartyLeaderComm_ResponseType = 2
	JoinPartyLeaderComm_LeaderNotReady JoinPartyLeaderComm_ResponseType = 3
	JoinPartyLeaderComm_UnknownPeer    JoinPartyLeaderComm_ResponseType = 4
)

// Enum value maps for JoinPartyLeaderComm_ResponseType.
var (
	JoinPartyLeaderComm_ResponseType_name = map[int32]string{
		0: "Unknown",
		1: "Success",
		2: "Timeout",
		3: "LeaderNotReady",
		4: "UnknownPeer",
	}
	JoinPartyLeaderComm_ResponseType_value = map[string]int32{
		"Unknown":        0,
		"Success":        1,
		"Timeout":        2,
		"LeaderNotReady": 3,
		"UnknownPeer":    4,
	}
)

func (x JoinPartyLeaderComm_ResponseType) Enum() *JoinPartyLeaderComm_ResponseType {
	p := new(JoinPartyLeaderComm_ResponseType)
	*p = x
	return p
}

func (x JoinPartyLeaderComm_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinPartyLeaderComm_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_join_party_proto_enumTypes[0].Descriptor()
}

func (JoinPartyLeaderComm_ResponseType) Type() protoreflect.EnumType {
	return &file_messages_join_party_proto_enumTypes[0]
}

func (x JoinPartyLeaderComm_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinPartyLeaderComm_ResponseType.Descriptor instead.
func (JoinPartyLeaderComm_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_messages_join_party_proto_rawDescGZIP(), []int{1, 0}
}

type JoinPartyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"` // the unique hash id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPartyRequest) Reset() {
	*x = JoinPartyRequest{}
	mi := &file_messages_join_party_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPartyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPartyRequest) ProtoMessage() {}

func (x *JoinPartyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_join_party_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPartyRequest.ProtoReflect.Descriptor instead.
func (*JoinPartyRequest) Descriptor() ([]byte, []int) {
	return file_messages_join_party_proto_rawDescGZIP(), []int{0}
}

func (x *JoinPartyRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type JoinPartyLeaderComm struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	ID            string                           `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`                                                     // unique hash id
	MsgType       string                           `protobuf:"bytes,2,opt,name=MsgType,proto3" json:"MsgType,omitempty"`                                           // unique hash id
	Type          JoinPartyLeaderComm_ResponseType `protobuf:"varint,3,opt,name=type,proto3,enum=messages.JoinPartyLeaderComm_ResponseType" json:"type,omitempty"` // result
	PeerIDs       []string                         `protobuf:"bytes,4,rep,name=PeerIDs,proto3" json:"PeerIDs,omitempty"`                                           // if Success , this will be the list of peers to form the ceremony, if fail , this will be the peers that are available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPartyLeaderComm) Reset() {
	*x = JoinPartyLeaderComm{}
	mi := &file_messages_join_party_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPartyLeaderComm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPartyLeaderComm) ProtoMessage() {}

func (x *JoinPartyLeaderComm) ProtoReflect() protoreflect.Message {
	mi := &file_messages_join_party_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPartyLeaderComm.ProtoReflect.Descriptor instead.
func (*JoinPartyLeaderComm) Descriptor() ([]byte, []int) {
	return file_messages_join_party_proto_rawDescGZIP(), []int{1}
}

func (x *JoinPartyLeaderComm) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *JoinPartyLeaderComm) GetMsgType() string {
	if x != nil {
		return x.MsgType
	}
	return ""
}

func (x *JoinPartyLeaderComm) GetType() JoinPartyLeaderComm_ResponseType {
	if x != nil {
		return x.Type
	}
	return JoinPartyLeaderComm_Unknown
}

func (x *JoinPartyLeaderComm) GetPeerIDs() []string {
	if x != nil {
		return x.PeerIDs
	}
	return nil
}

var File_messages_join_party_proto protoreflect.FileDescriptor

const file_messages_join_party_proto_rawDesc = "" +
	"\n" +
	"\x19messages/join_party.proto\x12\bmessages\"\"\n" +
	"\x10JoinPartyRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"\xf5\x01\n" +
	"\x13JoinPartyLeaderComm\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\aMsgType\x18\x02 \x01(\tR\aMsgType\x12>\n" +
	"\x04type\x18\x03 \x01(\x0e2*.messages.JoinPartyLeaderComm.ResponseTypeR\x04type\x12\x18\n" +
	"\aPeerIDs\x18\x04 \x03(\tR\aPeerIDs\"Z\n" +
	"\fResponseType\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\x12\v\n" +
	"\aTimeout\x10\x02\x12\x12\n" +
	"\x0eLeaderNotReady\x10\x03\x12\x0f\n" +
	"\vUnknownPeer\x10\x04B;Z9gitlab.com/mayachain/mayanode/bifrost/tss/go-tss/messagesb\x06proto3"

var (
	file_messages_join_party_proto_rawDescOnce sync.Once
	file_messages_join_party_proto_rawDescData []byte
)

func file_messages_join_party_proto_rawDescGZIP() []byte {
	file_messages_join_party_proto_rawDescOnce.Do(func() {
		file_messages_join_party_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_join_party_proto_rawDesc), len(file_messages_join_party_proto_rawDesc)))
	})
	return file_messages_join_party_proto_rawDescData
}

var file_messages_join_party_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_join_party_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_messages_join_party_proto_goTypes = []any{
	(JoinPartyLeaderComm_ResponseType)(0), // 0: messages.JoinPartyLeaderComm.ResponseType
	(*JoinPartyRequest)(nil),              // 1: messages.JoinPartyRequest
	(*JoinPartyLeaderComm)(nil),           // 2: messages.JoinPartyLeaderComm
}
var file_messages_join_party_proto_depIdxs = []int32{
	0, // 0: messages.JoinPartyLeaderComm.type:type_name -> messages.JoinPartyLeaderComm.ResponseType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messages_join_party_proto_init() }
func file_messages_join_party_proto_init() {
	if File_messages_join_party_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_join_party_proto_rawDesc), len(file_messages_join_party_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_join_party_proto_goTypes,
		DependencyIndexes: file_messages_join_party_proto_depIdxs,
		EnumInfos:         file_messages_join_party_proto_enumTypes,
		MessageInfos:      file_messages_join_party_proto_msgTypes,
	}.Build()
	File_messages_join_party_proto = out.File
	file_messages_join_party_proto_goTypes = nil
	file_messages_join_party_proto_depIdxs = nil
}
