FROM debian:bookworm-slim@sha256:5accafaaf0f2c0a3ee5f2dcd9a5f2ef7ed3089fe4ac6a9fc9b1cf16396571322

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  python3-pip=23.0.1+dfsg-1 \
  ca-certificates=20230311 \
  git=1:2.39.5-0+deb12u2 \
  curl=7.88.1-10+deb12u12 \
  jq=1.6-2.1 \
  libffi-dev=3.4.4-1 \
  libssl-dev=3.0.15-1~deb12u1 \
  openssl=3.0.15-1~deb12u1 \
  procps=2:4.0.2-3 \
  python3=3.11.2-1+b1 \
  libusb-1.0-0=2:1.0.26-1 && \
  rm -rf /var/lib/apt/lists/*

# Install Python packages globally (since we're in a container, this is safe)
RUN pip3 install --break-system-packages --no-cache-dir requests==2.32.3 retry==0.9.2 urllib3==2.2.2 web3==6.20.1 radix-engine-toolkit==2.1.1
