// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: thorchain/wasm/msg_exec.proto

package wasm

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	common "gitlab.com/mayachain/mayanode/common"
	gitlab_com_mayachain_mayanode_common "gitlab.com/mayachain/mayanode/common"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgWasmExec struct {
	Tx       common.Tx                                     `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx"`
	Asset    gitlab_com_mayachain_mayanode_common.Asset    `protobuf:"bytes,2,opt,name=asset,proto3,customtype=gitlab.com/mayachain/mayanode/common.Asset" json:"asset"`
	Amount   github_com_cosmos_cosmos_sdk_types.Uint       `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Uint" json:"amount"`
	Contract github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,4,opt,name=contract,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"contract,omitempty"`
	Msg      []byte                                        `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	Sender   github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,6,opt,name=sender,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"sender,omitempty"`
	Signer   github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,7,opt,name=signer,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"signer,omitempty"`
}

func (m *MsgWasmExec) Reset()         { *m = MsgWasmExec{} }
func (m *MsgWasmExec) String() string { return proto.CompactTextString(m) }
func (*MsgWasmExec) ProtoMessage()    {}
func (*MsgWasmExec) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c0e915ae6417048, []int{0}
}
func (m *MsgWasmExec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgWasmExec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgWasmExec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgWasmExec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgWasmExec.Merge(m, src)
}
func (m *MsgWasmExec) XXX_Size() int {
	return m.Size()
}
func (m *MsgWasmExec) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgWasmExec.DiscardUnknown(m)
}

var xxx_messageInfo_MsgWasmExec proto.InternalMessageInfo

func (m *MsgWasmExec) GetTx() common.Tx {
	if m != nil {
		return m.Tx
	}
	return common.Tx{}
}

func (m *MsgWasmExec) GetContract() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *MsgWasmExec) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *MsgWasmExec) GetSender() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *MsgWasmExec) GetSigner() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Signer
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgWasmExec)(nil), "types.MsgWasmExec")
}

func init() { proto.RegisterFile("thorchain/wasm/msg_exec.proto", fileDescriptor_1c0e915ae6417048) }

var fileDescriptor_1c0e915ae6417048 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcb, 0x4a, 0xf3, 0x40,
	0x14, 0xc7, 0x93, 0x5e, 0xf2, 0x7d, 0x4e, 0x15, 0x24, 0xb8, 0x08, 0x05, 0xd3, 0xe0, 0xc6, 0x22,
	0xb4, 0x43, 0xeb, 0x13, 0x34, 0x50, 0xc4, 0x45, 0x37, 0x41, 0x29, 0xb8, 0x29, 0xd3, 0xc9, 0x38,
	0x0d, 0xed, 0xcc, 0x94, 0x9c, 0xa9, 0xa6, 0x6f, 0xe1, 0x63, 0x75, 0xd9, 0xa5, 0xb8, 0x28, 0xd2,
	0xbe, 0x85, 0x2b, 0xc9, 0xc5, 0xdb, 0x46, 0xa4, 0xab, 0xf3, 0xe7, 0x9c, 0xdf, 0xf9, 0x91, 0x30,
	0x07, 0x9d, 0xea, 0x89, 0x8a, 0xe9, 0x84, 0x44, 0x12, 0x3f, 0x12, 0x10, 0x58, 0x00, 0x1f, 0xb1,
	0x84, 0xd1, 0xf6, 0x3c, 0x56, 0x5a, 0xd9, 0x55, 0xbd, 0x9c, 0x33, 0xa8, 0x7b, 0x82, 0x2c, 0x49,
	0x4e, 0x3d, 0x74, 0x30, 0x55, 0x42, 0x28, 0x59, 0x94, 0x1c, 0xac, 0x9f, 0x70, 0xc5, 0x55, 0x16,
	0x71, 0x9a, 0xf2, 0xee, 0xd9, 0xaa, 0x8c, 0x6a, 0x03, 0xe0, 0x43, 0x02, 0xa2, 0x9f, 0x30, 0x6a,
	0x7b, 0xa8, 0xa4, 0x13, 0xc7, 0xf4, 0xcc, 0x66, 0xad, 0x8b, 0xda, 0x85, 0xe0, 0x26, 0xf1, 0x2b,
	0xab, 0x4d, 0xc3, 0x08, 0x4a, 0x3a, 0xb1, 0x87, 0xa8, 0x4a, 0x00, 0x98, 0x76, 0x4a, 0x19, 0x74,
	0xf4, 0x01, 0xf5, 0xd2, 0xa6, 0xdf, 0x4d, 0xb9, 0x97, 0x4d, 0xe3, 0x82, 0x47, 0x7a, 0x46, 0xc6,
	0xe9, 0x10, 0x7f, 0x7d, 0x5a, 0x9a, 0xa4, 0x0a, 0x19, 0xfe, 0xbe, 0x13, 0xe4, 0x3e, 0xfb, 0x0a,
	0x59, 0x44, 0xa8, 0x85, 0xd4, 0x4e, 0xd9, 0x33, 0x9b, 0x07, 0x3e, 0x2e, 0x54, 0xe7, 0x3c, 0xd2,
	0x93, 0x45, 0xae, 0xa2, 0x0a, 0x84, 0x82, 0xa2, 0xb4, 0x20, 0x9c, 0xe2, 0xec, 0xf7, 0xdb, 0xb7,
	0x91, 0xd4, 0x41, 0xb1, 0x6e, 0x0f, 0xd0, 0x7f, 0xaa, 0xa4, 0x8e, 0x09, 0xd5, 0x4e, 0xc5, 0x33,
	0x9b, 0x87, 0x7e, 0xe7, 0x6d, 0xd3, 0x68, 0xfd, 0x41, 0xd3, 0xa3, 0xb4, 0x17, 0x86, 0x31, 0x03,
	0x08, 0x3e, 0x15, 0xf6, 0x31, 0x2a, 0x0b, 0xe0, 0x4e, 0x35, 0x35, 0x05, 0x69, 0xb4, 0xaf, 0x91,
	0x05, 0x4c, 0x86, 0x2c, 0x76, 0xac, 0x7d, 0xf5, 0x85, 0x20, 0x53, 0x45, 0x5c, 0xb2, 0xd8, 0xf9,
	0xb7, 0xbf, 0x2a, 0x13, 0xf8, 0xa3, 0xd5, 0xd6, 0x35, 0xd7, 0x5b, 0xd7, 0x7c, 0xdd, 0xba, 0xe6,
	0xd3, 0xce, 0x35, 0xd6, 0x3b, 0xd7, 0x78, 0xde, 0xb9, 0xc6, 0x5d, 0xff, 0xf7, 0xc7, 0x18, 0x47,
	0xf7, 0xb1, 0x02, 0x8d, 0xe7, 0x53, 0x8e, 0xb3, 0x11, 0x9d, 0x45, 0x4c, 0x6a, 0xc0, 0x3f, 0x2f,
	0x6f, 0x6c, 0x65, 0x27, 0x73, 0xf9, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xaa, 0x85, 0x62, 0x92,
	0x02, 0x00, 0x00,
}

func (m *MsgWasmExec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgWasmExec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgWasmExec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintMsgExec(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintMsgExec(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintMsgExec(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintMsgExec(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgExec(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Asset.Size()
		i -= size
		if _, err := m.Asset.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMsgExec(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Tx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintMsgExec(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMsgExec(dAtA []byte, offset int, v uint64) int {
	offset -= sovMsgExec(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgWasmExec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Tx.Size()
	n += 1 + l + sovMsgExec(uint64(l))
	l = m.Asset.Size()
	n += 1 + l + sovMsgExec(uint64(l))
	l = m.Amount.Size()
	n += 1 + l + sovMsgExec(uint64(l))
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovMsgExec(uint64(l))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovMsgExec(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovMsgExec(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovMsgExec(uint64(l))
	}
	return n
}

func sovMsgExec(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMsgExec(x uint64) (n int) {
	return sovMsgExec(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgWasmExec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMsgExec
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgWasmExec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgWasmExec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgExec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgExec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMsgExec
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMsgExec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMsgExec
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgExec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgExec
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgExec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = append(m.Contract[:0], dAtA[iNdEx:postIndex]...)
			if m.Contract == nil {
				m.Contract = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgExec
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgExec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = append(m.Msg[:0], dAtA[iNdEx:postIndex]...)
			if m.Msg == nil {
				m.Msg = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgExec
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgExec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = append(m.Sender[:0], dAtA[iNdEx:postIndex]...)
			if m.Sender == nil {
				m.Sender = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMsgExec
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMsgExec
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMsgExec
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = append(m.Signer[:0], dAtA[iNdEx:postIndex]...)
			if m.Signer == nil {
				m.Signer = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMsgExec(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMsgExec
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMsgExec
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMsgExec(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMsgExec
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgExec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMsgExec
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMsgExec
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMsgExec
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMsgExec
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMsgExec        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMsgExec          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMsgExec = fmt.Errorf("proto: unexpected end of group")
)
